name = "ansible-6"
collection = "ansible"
version = "6"
base_url = "https://docs.ansible.com/projects/ansible/6/"
content_selector = "div[role=main]"
deny_prefixes = []
max_pages = 12000
delay_seconds = 0.3
