name = "csi-external-provisioner-5.3"
collection = "csi-external-provisioner"
version = "5.3.0"
source_type = "git"
repo_url = "https://github.com/kubernetes-csi/external-provisioner"
git_ref = "1a7e9381439295969ad0336f1e21791f7dc3abe8"
docs_paths = ["doc", "README.md", "CONTRIBUTING.md"]
sparse_paths = ["doc", "README.md", "CONTRIBUTING.md"]
